name: docs

on:
  push:
    branches: master

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:dev
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate Dart API Docs
      run: |
        pub get
        dartdoc --output build
        touch build/.nojekyll
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      # env:
      #   PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   PUBLISH_BRANCH: gh-pages
      #   PUBLISH_DIR: ./build
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        allow_empty_commit: false
    - name: notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TelegramBotToken }}
        chatId: ${{ secrets.TelegramTarget }}
        jobStatus: ${{ job.status }}
